# Generated by Django 5.0.1 on 2024-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_receiver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='receiver_email',
        ),
        migrations.AddField(
            model_name='site',
            name='contact_receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
