# Generated by Django 5.0.1 on 2024-06-11 03:58

import django.db.models.deletion
import portfolio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_resume_created_at_resume_key_resume_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_id', models.TextField(default=portfolio.utils.generate_urlsafe_key, editable=False, unique=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume')),
            ],
        ),
    ]
